apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-backend
  template:
    metadata:
      labels:
        app: rust-backend
    spec:
      containers:
        - name: rust-backend
          image: k8s-rust-fullstack-demo_backend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: greeting
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password
