apiVersion: v1
kind: Service
metadata:
  name: rust-backend
spec:
  type: NodePort
  selector:
    app: rust-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
