apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
    spec:
      containers:
        - name: simple-frontend
          image: k8s-rust-fullstack-demo_frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
